on:
  workflow_dispatch

name: Azure Container Deployment
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    # Checkout code
    - uses: actions/checkout@main

      # Log into Azure
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

      # Deploy ARM template
    - uses: azure/webapps-deploy@v2
      with:
        app-name: 'qwsl45aveglgo-dev'
        images: 'docker.io/ldelpozo/razorpagestestsample:8'
